export const TOPIC_KEYS = [
  "daily life",
  "greetings",
  "travel",
  "food",
  "shopping",
  "family",
  "friends",
  "work",
  "business",
  "university",
  "school",
  "technology",
  "design",
  "social media",
  "creators",
  "coding",
  "anime",
  "fashion",
  "music scenes",
  "health",
  "fitness",
  "emotions",
  "communication",
  "movies",
  "music",
  "gaming",
  "culture",
  "transportation",
  "housing",
  "money",
  "nature",
] as const;

export type TopicKey = (typeof TOPIC_KEYS)[number];

export const DISCOVER_TOPIC_KEYS: TopicKey[] = [...TOPIC_KEYS];

export const HOME_TOPIC_KEYS: TopicKey[] = [
  "daily life",
  "travel",
  "food",
  "work",
  "technology",
  "communication",
  "movies",
  "nature",
];

export const ONBOARDING_TOPIC_KEYS: TopicKey[] = [...TOPIC_KEYS];

export const RELATED_TOPIC_GROUPS: Record<TopicKey, TopicKey[]> = {
  "daily life": ["greetings", "family", "friends", "housing", "communication"],
  greetings: ["daily life", "communication", "friends", "travel", "family"],
  travel: ["transportation", "housing", "food", "shopping", "culture"],
  food: ["daily life", "shopping", "family", "health", "travel"],
  shopping: ["money", "daily life", "travel", "business", "housing"],
  family: ["daily life", "friends", "housing", "emotions", "food"],
  friends: ["communication", "social media", "emotions", "family", "daily life"],
  work: ["business", "technology", "communication", "money", "design"],
  business: ["work", "money", "communication", "technology", "travel"],
  university: ["school", "work", "technology", "communication", "culture"],
  school: ["university", "daily life", "communication", "technology", "culture"],
  technology: ["work", "design", "social media", "gaming", "business"],
  design: ["technology", "movies", "music", "culture", "social media"],
  "social media": ["communication", "friends", "technology", "design", "creators"],
  creators: ["social media", "music scenes", "fashion", "gaming", "coding"],
  coding: ["technology", "design", "work", "gaming", "business"],
  anime: ["movies", "culture", "music scenes", "gaming", "friends"],
  fashion: ["design", "social media", "creators", "shopping", "culture"],
  "music scenes": ["music", "creators", "fashion", "culture", "friends"],
  health: ["fitness", "food", "daily life", "emotions", "nature"],
  fitness: ["health", "food", "daily life", "nature", "emotions"],
  emotions: ["friends", "family", "health", "communication", "music"],
  communication: ["friends", "social media", "work", "greetings", "emotions"],
  movies: ["music", "culture", "design", "friends", "gaming"],
  music: ["movies", "culture", "emotions", "friends", "design"],
  gaming: ["technology", "social media", "movies", "friends", "music"],
  culture: ["travel", "movies", "music", "school", "nature"],
  transportation: ["travel", "daily life", "work", "shopping", "housing"],
  housing: ["daily life", "family", "travel", "shopping", "transportation"],
  money: ["shopping", "business", "work", "daily life", "travel"],
  nature: ["travel", "health", "fitness", "culture", "housing"],
};

export const TOPIC_ICON_EMOJI: Record<TopicKey, string> = {
  "daily life": "Home",
  greetings: "Sparkles",
  travel: "Plane",
  food: "UtensilsCrossed",
  shopping: "ShoppingBag",
  family: "Users",
  friends: "MessagesSquare",
  work: "Briefcase",
  business: "LineChart",
  university: "GraduationCap",
  school: "NotebookPen",
  technology: "Laptop",
  design: "Palette",
  "social media": "Smartphone",
  creators: "Video",
  coding: "Code2",
  anime: "Sparkles",
  fashion: "Shirt",
  "music scenes": "Music2",
  health: "HeartPulse",
  fitness: "Dumbbell",
  emotions: "Smile",
  communication: "MessageCircle",
  movies: "Film",
  music: "Music2",
  gaming: "Gamepad2",
  culture: "Landmark",
  transportation: "Bus",
  housing: "Building2",
  money: "Wallet",
  nature: "Leaf",
};
