export const TOPIC_KEYS = [
  "daily life",
  "greetings",
  "travel",
  "food",
  "shopping",
  "family",
  "friends",
  "work",
  "business",
  "university",
  "school",
  "technology",
  "design",
  "social media",
  "creators",
  "coding",
  "anime",
  "fashion",
  "music scenes",
  "health",
  "fitness",
  "emotions",
  "communication",
  "movies",
  "music",
  "gaming",
  "culture",
  "transportation",
  "housing",
  "money",
  "nature",
] as const;

export type TopicKey = (typeof TOPIC_KEYS)[number];

export const DEFAULT_TOPIC: TopicKey = "daily life";

export const TOPIC_ALIASES: Record<string, TopicKey> = {
  "core basics": "daily life",
  basics: "daily life",
  "daily basics": "daily life",
  greetings: "greetings",
  travel: "travel",
  food: "food",
  shopping: "shopping",
  family: "family",
  friends: "friends",
  work: "work",
  business: "business",
  university: "university",
  school: "school",
  technology: "technology",
  design: "design",
  "social media": "social media",
  social: "social media",
  creators: "creators",
  creator: "creators",
  coding: "coding",
  programming: "coding",
  anime: "anime",
  manga: "anime",
  fashion: "fashion",
  style: "fashion",
  "music scenes": "music scenes",
  concerts: "music scenes",
  health: "health",
  fitness: "fitness",
  emotions: "emotions",
  communication: "communication",
  movies: "movies",
  movie: "movies",
  music: "music",
  gaming: "gaming",
  games: "gaming",
  culture: "culture",
  transportation: "transportation",
  transport: "transportation",
  housing: "housing",
  home: "housing",
  money: "money",
  finance: "money",
  nature: "nature",
};
